export const constances = {
    RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
    FETCH_MESSAGES: 'FETCH_MESSAGES',
    SENT_MESSAGE: 'SENT_MESSAGE',

    LOGIN: 'LOGIN',
    SIGN_UP: 'SIGN_UP',
    LOGOUT: 'LOGOUT',
    LOGIN_RESULT: 'LOGIN_RESULT',
    SET_COOKIE: 'SET_COOKIE',

    ADMIN_SIGNIN: 'ADMIN_LOGIN',
    ADMIN_SIGNOUT: 'ADMIN_SIGNOUT',
    ADMIN_FETCH_ROOMS: 'ADMIN_FETCH_ROOMS',
    ADMIN_SELECT_ROOM: 'ADMIN_SELECT_ROOM',
    ADMIN_FETCH_MESSAGES: 'ADMIN_FETCH_MESSAGES',
    ADMIN_RECEIVE_MESSAGE: 'ADMIN_RECEIVE_MESSAGE'
}