export const constance = {
    FETCH_CATEGORY: 'FETCH_CATEGORY',
    SELECT_CATEGORY: 'SELECT_CATEGORY',

    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    SELECT_PRODUCT: 'SELECT_PRODUCT',
    FETCH_PRODUCTS_BY_CATEGORY: 'FETCH_PRODUCTS_BY_CATEGORY',

    ADD_INTO_CART: 'ADD_INTO_CART',
    DISCARD_FROM_CART: 'DISCARD_FROM_CART',
    DISCARD_FROM_CART_ALL: 'DISCARD_FROM_CART_ALL'
}