export const constance = {
    FETCH_CATEGORY: 'FETCH_CATEGORY',
    SELECT_CATEGORY: 'SELECT_CATEGORY',

    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    SELECT_PRODUCT: 'SELECT_PRODUCT',
    FETCH_PRODUCTS_BY_CATEGORY: 'FETCH_PRODUCTS_BY_CATEGORY',
    SEARCH_PRODUCTS: 'SEARCH_PRODUCTS',

    ADD_INTO_CART: 'ADD_INTO_CART',
    DISCARD_FROM_CART: 'DISCARD_FROM_CART',
    DISCARD_FROM_CART_ALL: 'DISCARD_FROM_CART_ALL',

    UPDATE_PRODUCT_TITLE: 'UPDATE_PRODUCT_TITLE',
    UPDATE_VIEW_TYPE: 'UPDATE_VIEW_TYPE',
    UPDATE_NAVBAR_MODAL: 'UPDATE_NAVBAR_MODAL',
    UPDATE_ERROR_STATUS: 'UPDATE_ERROR_STATUS',

    RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
    FETCH_MESSAGES: 'FETCH_MESSAGES',
    SENT_MESSAGE: 'SENT_MESSAGE',

    LOGIN: 'LOGIN',
    SIGN_UP: 'SIGN_UP',
    LOGOUT: 'LOGOUT',
    LOGIN_RESULT: 'LOGIN_RESULT',
    SET_COOKIE: 'SET_COOKIE',

    ADMIN_SIGNIN: 'ADMIN_LOGIN',
    ADMIN_SIGNOUT: 'ADMIN_SIGNOUT',
    ADMIN_FETCH_ROOMS: 'ADMIN_FETCH_ROOMS',
    ADMIN_SELECT_ROOM: 'ADMIN_SELECT_ROOM',
    ADMIN_FETCH_MESSAGES: 'ADMIN_FETCH_MESSAGES',
    ADMIN_RECEIVE_MESSAGE: 'ADMIN_RECEIVE_MESSAGE'
}