export { default as Home } from './Home'
export { default as Category } from './Category'
export { default as ProductInfo } from './ProductInfo'
export { default as Cart } from './Cart'
export { default as Admin } from './Admin'